sonar.projectKey=system-design
sonar.projectName=system-design
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.spec.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Local SonarQube setup
sonar.host.url=http://localhost:9000
sonar.login=sqp_cdfc67ffa06005db9b4383fa918ea46a39e2d493
